### PR TITLE
UI: more info

### PR DESCRIPTION
**Pull request by sarumpaet**
These commits provide better interlinking with the main Berlin FF page and address some recent user confusion (see mailinglist).

### CODE REVIEW

**Comment by cholin** [comment]
When I try this locally the whole design is getting worse. Was this intentionally?  See the image below (in comparsion to http://config.berlin.freifunk.net):
2015-01-27-152416_1366x768_scrot

I find the current solution better but maybe I'm the only one. What do others think? @andrenarchy, @geirkairam or @booo ?

**Comment by sarumpaet** [comment]
Sorry, there was a typo, please try again.

**Comment by cholin** [comment]
Looks still the same in Chromium and Firefox (no cached css).

**Comment by sarumpaet** [comment]
I tested it. It looks fine for me. Are you sure you got the latest version? I just amended the commit and force pushed. bc8876a just centers one line I missed before.

**Comment by cholin** [comment]
Tested with b9c0d916895e0858e6f0e25063032dfa734e0f51 and looks like the following:

2015-01-27-171452_1366x768_scrot

**Comment by sarumpaet** [comment]
That commit is not subject to this pull request (anymore) as I force pushed fixes after your first comment here. Please try bc8876a.

**Comment by sarumpaet** [comment]
If I can help, let me know. bc8876a should look like this:
bip

**Comment by cholin** [comment]
I just looked at the prefix and as both commit hashes started with a `b` and in the hurry I missed that they differ. I've now your changesets locally running and they look the same as your posted image. I've some suggestions but had not the the time to bring them to words. Give some time and I will give you feedback here.

**Comment by cholin** [comment]
I personally think this big headline is a step backwards. As well I don't like whole paragraphs emphasized with `<b></b>`. I merge this now and apply some refactoring regarding text and design.

**Comment by cholin** [comment]
Applied my changes with 01d03159350f12627a5748c06ea93be7bca5fd15 and 7699134512fa7a6e1746a471040977075f5be432 (pushed this as well on http://config.berlin.freifunk.net). If you don't like my changes we can discuss this in a new issue.

**Comment by andrenarchy** [comment]
One remark: *never* use `<b>` and `<i>`, see crime 4 in http://line25.com/articles/10-html-tag-crimes-you-really-shouldnt-commit

**Pull request merged**
